// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjTKFeeDpyl5YU54C7gJ3NZch5Eq2Okts',
    appId: '1:393067921306:web:59f8add522c8c79bea4423',
    messagingSenderId: '393067921306',
    projectId: 'flutter-starter-379cd',
    authDomain: 'flutter-starter-379cd.firebaseapp.com',
    storageBucket: 'flutter-starter-379cd.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJuSHoLC2qDkzeAFPrUSvOK2oPTBCmflw',
    appId: '1:393067921306:android:79dcc734f44923adea4423',
    messagingSenderId: '393067921306',
    projectId: 'flutter-starter-379cd',
    storageBucket: 'flutter-starter-379cd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWuJwUOJtEzY_QVP6UINt_qTibSgRwRj0',
    appId: '1:393067921306:ios:453db5b8a81257deea4423',
    messagingSenderId: '393067921306',
    projectId: 'flutter-starter-379cd',
    storageBucket: 'flutter-starter-379cd.appspot.com',
    iosBundleId: 'com.example.firebaseexample',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWuJwUOJtEzY_QVP6UINt_qTibSgRwRj0',
    appId: '1:393067921306:ios:f4c9caad9eab5b71ea4423',
    messagingSenderId: '393067921306',
    projectId: 'flutter-starter-379cd',
    storageBucket: 'flutter-starter-379cd.appspot.com',
    iosBundleId: 'com.example.firebaseexample.RunnerTests',
  );
}
